Refactor Zsh functions and scripts for improved readability and consistency
- Updated indentation in various Zsh functions and scripts to use tabs for consistency.
- Added new Zsh configuration files for Docker, aliases, Homebrew, and more.
- Removed deprecated autoload.sh file and replaced it with individual configuration files.
- Enhanced history management in Zsh with merging logic for .zsh_history files.
- Introduced new aliases for Git and Terraform commands for easier usage.
- Added support for Starship prompt installation in Zsh configuration.
- Improved weather and wallpaper functions for better error handling and output.
- Updated zstyle configurations for enhanced completion experience in Zsh.

diff --git a/containers/maestral/start b/containers/maestral/start
--- a/containers/maestral/start
+++ b/containers/maestral/start
@@ -1,16 +1,16 @@
 maestral_root="$DOTFILES/maestral"
 
 docker compose \
-    -f "$maestral_root/docker-compose.yml" \
-    down --volumes --remove-orphans
+	-f "$maestral_root/docker-compose.yml" \
+	down --volumes --remove-orphans
 
 # docker rmi bernardolm/maestral:latest
 
 github_repo="samschott/maestral"
 
 curl -s \
-    -o "$maestral_root/Dockerfile" \
-    https://raw.githubusercontent.com/$github_repo/refs/heads/main/Dockerfile
+	-o "$maestral_root/Dockerfile" \
+	https://raw.githubusercontent.com/$github_repo/refs/heads/main/Dockerfile
 
 api_url="https://api.github.com/repos/$github_repo/releases/latest"
 
@@ -18,18 +18,18 @@ export VERSION
 VERSION=$(curl -sL "${api_url}" | jq -r '.tag_name')
 
 [ -z "$VERSION" ] && {
-    echo "Failed to fetch the latest version from GitHub API."
-    exit 1
+	echo "Failed to fetch the latest version from GitHub API."
+	exit 1
 }
 
 echo "Using Maestral version: $VERSION"
 
 docker compose \
-    -f "$maestral_root/docker-compose.yml" \
-    up -d --build --remove-orphans --force-recreate
+	-f "$maestral_root/docker-compose.yml" \
+	up -d --build --remove-orphans --force-recreate
 
 echo "Everything is fine, you will now see the logs"
 
 docker compose \
-    -f "$maestral_root/docker-compose.yml" \
-    logs --follow --timestamps --tail=100 maestral
+	-f "$maestral_root/docker-compose.yml" \
+	logs --follow --timestamps --tail=100 maestral
