Improving pre install script

diff --git a/pre-install b/pre-install
--- a/pre-install
+++ b/pre-install
@@ -14,64 +14,103 @@
 
 # ---------------------------------------------------------------------------
 
-# apt update
-# apt --yes upgrade
-# apt install --yes \
-#     curl \
-#     git \
-#     make \
-#     python3-pip \
-#     sudo \
-#     ttf-mscorefonts-installer
+reset
 
-# export TERM=xterm-256color
-# export NO_COLOR=0
+set -e
 
-pwd
-env | sort
+export TERM=xterm-256color
+export NO_COLOR=0
 
 # shellcheck source=/dev/null
-source ./zsh/init/10_debug.zsh
+HOME=$(eval echo "~${SUDO_USER}") source ./zsh/startup/.zshenv ./zsh/functions/log_starting
 
-# shellcheck source=/dev/null
-HOME=$(eval echo "~${SUDO_USER}") source ./zsh/init/30_env.zsh
+sources_list_bkp_path="/etc/apt/sources.list.d-${TODAY}-${NOW}"
 
-# apt_sources_found=$(find /etc/apt/sources.list.d/ -name '*.list' | wc -l)
-# echo "${apt_sources_found} sources file found"
+alias lsa='ls -lah'
 
-# # Move this do shell command into dotbot apt config
-# if [ "${apt_sources_found}" -eq 0 ]; then
-#     # check if is a link before
-#     ([ -d "/etc/apt/sources.list.d" ] || [ -L "/etc/apt/sources.list.d" ]) && _
-#         sudo mv /etc/apt/sources.list.d /etc/apt/sources.list.d.$(date +"%m/%d/%Y %H:%M")
-#     ln -sf "${SYNC_DOTFILES}/etc/apt/sources.list.d" /etc/apt/sources.list.d
-#     # shellcheck source=/dev/null
-#     source ./zsh/apt.zsh
-#     HOME=$(eval echo "~${SUDO_USER}") apt_keys_recovery
-#     apt update
-# fi
+function exit_defer() {
+    echo 'finish'
+    set +e
+    exit 0
+}
 
-ls -lah
+function err_defer() {
+    echo 'trying rollback after error'
+    [ -d "${sources_list_bkp_path}" ] && \
+        sudo mv "${sources_list_bkp_path}" /etc/apt/sources.list.d
+    set +e
+    exit 1
+}
 
-echo "sanitizing git submodule"
-cat < .gitmodules | grep 'submodule' | while read -r item; do
-    item=$(echo "${item}" | sed -E 's/.*\"(.*)\".*/\1/')
-    echo "${item}"
-    if [ -z "$(ls -A ./"$item")" ]; then
-        git submodule deinit --force --all "${item}" 2>/dev/null
-        rm -rf "${item}" ".git/modules/${item}" 2>/dev/null
+function apt_init() {
+    sudo apt-get update
+    sudo apt-get --yes upgrade
+    sudo apt-get install --yes \
+        curl \
+        git \
+        make \
+        python3-pip \
+        sudo \
+        ttf-mscorefonts-installer
+}
+
+function apt_sources_count_list_files() {
+    apt_sources_found=$(find /etc/apt/sources.list.d/ -name '*.list' 2>/dev/null | wc -l || 0)
+    echo "${apt_sources_found} sources file found"
+}
+
+function apt_sources_link() {
+    echo 'apt updating, upgrading and installing basic packages'
+
+    apt_sources_count_list_files
+
+    if [ "${apt_sources_found}" -eq 0 ]; then
+        echo 'moving apt sources and linking my own list files'
+        # check if is a link before
+        if [ -d "/etc/apt/sources.list.d" ] || [ -L "/etc/apt/sources.list.d" ]; then
+            echo 'sources list path not exist or is a sym link. backup it.'
+            sudo mv /etc/apt/sources.list.d "${sources_list_bkp_path}"
+        fi
+        apt_sources_count_list_files
+
+        sudo ln -sf "${SYNC_DOTFILES}/etc/apt/sources.list.d" /etc/apt/sources.list.d
+
+        # shellcheck source=/dev/null
+        source ./zsh/functions/apt_keys_recovery
+        HOME=$(eval echo "~${SUDO_USER}") apt_keys_recovery
+        sudo apt update
     fi
+}
+
+trap exit_defer EXIT
+trap err_defer ERR
+
+# apt_init
+
+# Move this do shell command into dotbot apt config
+# apt_sources_link
+
+echo "sanitizing git submodules"
+cat < .gitmodules | grep '\[submodule' | while read -r item; do
+    name=$(echo "$item" | sed -E 's/.*"(.*)".*/\1/g')
+    path=$(git config --file ".gitmodules" --get "submodule.${name}.path")
+    url=$(git config --file ".gitmodules" --get "submodule.${name}.url")
+
+    echo "    submodule ${name} in ${path} by ${url}"
+
+    if [ -d "${path}" ]; then
+        echo "    ${path} not empty, purging it."
+
+        git submodule deinit --force "${path}" 1>/dev/null || true
+
+        /bin/rm -rf "${path}"
+        /bin/rm -rf ".${path}"
+    fi
+
+    echo "    adding submodule ${name}"
+    git submodule add --force "${url}" "${path}" 1>/dev/null
+
+    echo -e "    done\n    ---"
 done
-
-ls -lah
-
-# echo "adding git submodule"
-# cat < .gitmodules | grep 'url' | while read -r item; do
-#     item=$(echo "${item}" | sed 's/ //g' | cut -d'=' -f2)
-#     echo "${item}"
-#     git submodule add --force "${item}" 2>/dev/null
-# done
-
-# ls -lah
 
 # git submodule update --init --recursive --remote
